"""Create user

Revision ID: 1689c313cf6c
Revises: 4886e5237828
Create Date: 2025-08-02 10:24:34.828348

"""

# pylint: disable=all
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "1689c313cf6c"
down_revision = "4886e5237828"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ui_language_code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column(
            "last_story_language_code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
        sa.Column("use_last_story_language", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_story_language_code"],
            ["supported_story_language.language_code"],
        ),
        sa.ForeignKeyConstraint(
            ["ui_language_code"],
            ["supported_user_language.language_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
