"""Add last_story_language_code

Revision ID: 0ef9265bc40c
Revises: 0d7d5b809799
Create Date: 2025-08-03 16:14:18.071664

"""

# pylint: disable=all
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ef9265bc40c"
down_revision = "0d7d5b809799"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_story_language_code", sa.String(), nullable=True))
    op.add_column("users", sa.Column("use_last_story_language", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "use_last_story_language")
    op.drop_column("users", "last_story_language_code")
    # ### end Alembic commands ###
