"""rename_last_story_language_code_to_story_language_code

Revision ID: f11c6eaabcd2
Revises: 0ef9265bc40c
Create Date: 2025-08-03 22:21:24.880846

"""

import sqlalchemy as sa

# pylint: disable=all
from alembic import op

# revision identifiers, used by Alembic.
revision = "f11c6eaabcd2"
down_revision = "0ef9265bc40c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "last_story_language_code", new_column_name="story_language_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "story_language_code", new_column_name="last_story_language_code")
    # ### end Alembic commands ###
