from typing import Any, Protocol


class Cache(Protocol):
    async def set(self, key: str, value: str, ttl: int) -> None: ...
    async def get(self, key: str) -> Any: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def expire(self, key: str, ttl: int) -> None: ...
